# Generated by Django 4.2 on 2026-02-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
