# Generated by Django 4.2 on 2026-02-26 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_alter_subject_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='start_time',
        ),
    ]
