# Generated by Django 4.2 on 2026-06-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_codingquestion_task_tasksubmission_codingsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasksubmission',
            name='student',
        ),
        migrations.RemoveField(
            model_name='tasksubmission',
            name='task',
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='sample_input',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='sample_output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskSubmission',
        ),
    ]
